# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  red-secret:
    runs-on: [self-hosted]
    
    steps:
    
    - name: Print
      run: echo test

